CREATE TABLE FACULTY
(
	ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	NAME VARCHAR(30) NOT NULL UNIQUE,
)
GO

CREATE TABLE GROUPS
(
	ID UNIQUEIDENTIFIER  NOT NULL PRIMARY KEY,
	NAME VARCHAR(10) NOT NULL,
	HEAD_GROUP UNIQUEIDENTIFIER,
	FACULTY_ID UNIQUEIDENTIFIER NOT NULL,
)
GO

CREATE TABLE LESSONS
(
	GROUP_ID UNIQUEIDENTIFIER NOT NULL,
	PREPOD_ID UNIQUEIDENTIFIER NOT NULL,
	STUDY_ID CHAR(20) NOT NULL,
	PRIMARY KEY(GROUP_ID, PREPOD_ID, STUDY_ID)
)
GO

CREATE TABLE PREPODS
(
	ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	LAST_NAME VARCHAR(120) NOT NULL,
	FIRST_NAME VARCHAR(120),
	FACULTY_ID UNIQUEIDENTIFIER NOT NULL
)
GO

CREATE TABLE RAITING
(
	ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	DATE DATE NOT NULL,
	VAL NUMERIC,
	STUDENT_ID UNIQUEIDENTIFIER NOT NULL,
	STUDY_ID CHAR(20) NOT NULL,
	PREPODS_ID UNIQUEIDENTIFIER NOT NULL,
	IS_ABSENT VARCHAR(3) DEFAULT 'YES',
	CONSTRAINT chkValue CHECK (VAL>3 AND VAL<=10)
)
GO

CREATE TABLE STUDENTS
(
	ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	LAST_NAME VARCHAR(60) NOT NULL,
	FIRST_NAME VARCHAR(30),
	GROUP_ID UNIQUEIDENTIFIER,
)
GO

CREATE TABLE STUDY_LOAD
(
	ID CHAR(20) NOT NULL PRIMARY KEY,
	hours NUMERIC,
	SUBJECT_ID UNIQUEIDENTIFIER NOT NULL,
	Type_STYDY_ID UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT chkStudyLoad CHECK (hours>=0)
)
GO

CREATE TABLE SUBJECTS
(
	ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	NAME VARCHAR(120) NOT NULL,
	FACULTY_ID UNIQUEIDENTIFIER,
)
GO

CREATE TABLE TYPE_STUDY_LOAD
(
	ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	NAME VARCHAR(120) NOT NULL UNIQUE,
)
GO

ALTER TABLE GROUPS
	ADD FOREIGN KEY (HEAD_GROUP) REFERENCES STUDENTS
ALTER TABLE GROUPS
	ADD FOREIGN KEY (FACULTY_ID) REFERENCES FACULTY
GO

ALTER TABLE LESSONS
	ADD FOREIGN KEY (GROUP_ID) REFERENCES GROUPS
ALTER TABLE LESSONS
	ADD FOREIGN KEY (PREPOD_ID) REFERENCES PREPODS
ALTER TABLE LESSONS
	ADD FOREIGN KEY (STUDY_ID) REFERENCES STUDY_LOAD
GO

ALTER TABLE PREPODS
	ADD FOREIGN KEY (FACULTY_ID) REFERENCES FACULTY
GO

ALTER TABLE RAITING
	ADD FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS
ALTER TABLE RAITING
	ADD FOREIGN KEY (STUDY_ID) REFERENCES STUDY_LOAD
ALTER TABLE RAITING
	ADD FOREIGN KEY (PREPODS_ID) REFERENCES PREPODS
GO

ALTER TABLE STUDENTS
	ADD FOREIGN KEY (GROUP_ID) REFERENCES GROUPS
GO

ALTER TABLE STUDY_LOAD
	ADD FOREIGN KEY (Type_STYDY_ID) REFERENCES TYPE_STUDY_LOAD
ALTER TABLE STUDY_LOAD
	ADD FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS
GO

ALTER TABLE SUBJECTS
	ADD FOREIGN KEY (FACULTY_ID) REFERENCES FACULTY
GO
